<?php 
require_once("ChrFinder.php");
class CAChrCalculator extends ChrFinder {
	// function to calculate the origins of post-gold rush California (like albion's seed)
	public function calc($arrayName, $rFile, $analysisFileName)
	{
		// We need to calculate the chr here before replacing the text of the html file or updating the map javascript files
		// First, loop through the parents of the root and extract their birthplace iso
		$chrCount = 0;
		$parentISO = $this-> findParentBirthPlaces($arrayName,$chrCount);
		$chrrootArray = array();
		$this->writeDataToFile($rFile,$chrCount,$chrrootArray,$parentISO);
		// Now we open the .js file to write the dynamic data to it.
		// Read in the text of the js so that we can manipulate it
		// Place pointer back at begining of array

		$CALIFORNIA = 0;
		$MEX = 0;
		$CAN = 0;
		$EURO = 0;
		$WEST = 0;
		$SOUTH = 0;
		$MIDWEST = 0;
		$EAST = 0;
		$NEWENGLAND = 0;
		$USOther = 0;
		$Unknown = 0;
		$knownUnknown = 0;
		$other = 0;
		
		foreach($chrrootArray as $key => $val)
		{
			switch($key){
				case 'US-CA': $CALIFORNIA += $val;
				break;
				case 'MX':
				case 'MX-DIF':
				case 'MX-AGU':
				case 'MX-BCN':
				case 'MX-BCS':
				case 'MX-CAM':
				case 'MX-COA':
				case 'MX-COL':
				case 'MX-CHP':
				case 'MX-CHH':
				case 'MX-DUR':
				case 'MX-GRO':
				case 'MX-GUA':
				case 'MX-HID':
				case 'MX-JAL':
				case 'MX-MEX':
				case 'MX-MIC':
				case 'MX-MOR':
				case 'MX-NAY':
				case 'MX-NLE':
				case 'MX-OAX':
				case 'MX-PUE':
				case 'MX-QUE':
				case 'MX-ROO':
				case 'MX-SLP':
				case 'MX-SIN':
				case 'MX-SON':
				case 'MX-TAB':
				case 'MX-TAM':
				case 'MX-TLA':
				case 'MX-VER':
				case 'MX-YUC':
				case 'MX-ZAC': $MEX += $val;
				break;
				case 'CA':
				case 'CA-AB':
				case 'CA-BC':
				case 'CA-MB':
				case 'CA-NB':
				case 'CA-NF':
				case 'CA-NS':
				case 'CA-ON':
				case 'CA-PE':
				case 'CA-QC':
				case 'CA-SK':
				case 'CA-NT':
				case 'CA-YT': $CAN += $val;
				break;
				case 'AL': 
				case 'AL-BR': 
				case 'AL-BU': 
				case 'AL-DL': 
				case 'AL-DV': 
				case 'AL-DI': 
				case 'AL-DR': 
				case 'AL-EL': 
				case 'AL-FR': 
				case 'AL-GR': 
				case 'AL-GJ': 
				case 'AL-HA': 
				case 'AL-KA': 
				case 'AL-ER': 
				case 'AL-KO': 
				case 'AL-KR': 
				case 'AL-KC': 
				case 'AL-KU': 
				case 'AL-LA': 
				case 'AL-LE': 
				case 'AL-LB': 
				case 'AL-LU': 
				case 'AL-MM': 
				case 'AL-MK': 
				case 'AL-MT': 
				case 'AL-MR': 
				case 'AL-PQ': 
				case 'AL-PR': 
				case 'AL-PG': 
				case 'AL-PU': 
				case 'AL-SR': 
				case 'AL-SK': 
				case 'AL-SH': 
				case 'AL-TE': 
				case 'AL-TR': 
				case 'AL-TP': 
				case 'AL-VL': 
				case 'AD': 
				case 'RU': 
				case 'RU-AD': 
				case 'RU-AL': 
				case 'RU-BA': 
				case 'RU-BU': 
				case 'RU-CE': 
				case 'RU-CU': 
				case 'RU-DA': 
				case 'RU-IN': 
				case 'RU-KB': 
				case 'RU-KL': 
				case 'RU-KC': 
				case 'RU-KR': 
				case 'RU-KK': 
				case 'RU-KO': 
				case 'RU-ME': 
				case 'RU-MO': 
				case 'RU-SA': 
				case 'RU-SE': 
				case 'RU-TA': 
				case 'RU-TY': 
				case 'RU-UD': 
				case 'RU-ALT': 
				case 'RU-KHA': 
				case 'RU-KDA': 
				case 'RU-KYA': 
				case 'RU-PRI': 
				case 'RU-STA': 
				case 'RU-AMU': 
				case 'RU-ARK': 
				case 'RU-AST': 
				case 'RU-BEL': 
				case 'RU-BRY': 
				case 'RU-CHE': 
				case 'RU-CHI': 
				case 'RU-IRK': 
				case 'RU-IVA': 
				case 'RU-KGD': 
				case 'RU-KLU': 
				case 'RU-KAM': 
				case 'RU-KEM': 
				case 'RU-KIR': 
				case 'RU-KOS': 
				case 'RU-KGN': 
				case 'RU-KRS': 
				case 'RU-LEN': 
				case 'RU-LIP': 
				case 'RU-MAG': 
				case 'RU-MOS': 
				case 'RU-MUR': 
				case 'RU-NIZ': 
				case 'RU-NGR': 
				case 'RU-NVS': 
				case 'RU-OMS': 
				case 'RU-ORE': 
				case 'RU-ORL': 
				case 'RU-PNZ': 
				case 'RU-PER': 
				case 'RU-PSK': 
				case 'RU-ROS': 
				case 'RU-RYA': 
				case 'RU-SAK': 
				case 'RU-SAM': 
				case 'RU-SAR': 
				case 'RU-SMO': 
				case 'RU-SVE': 
				case 'RU-TAM': 
				case 'RU-TOM': 
				case 'RU-TUL': 
				case 'RU-TVE': 
				case 'RU-TYU': 
				case 'RU-ULY': 
				case 'RU-VLA': 
				case 'RU-VGG': 
				case 'RU-VLG': 
				case 'RU-VOR': 
				case 'RU-YAR': 
				case 'RU-MOW': 
				case 'RU-SPE': 
				case 'RU-YEV': 
				case 'RU-AGB': 
				case 'RU-CHU': 
				case 'RU-EVE': 
				case 'RU-KHM': 
				case 'RU-KOP': 
				case 'RU-KOR': 
				case 'RU-NEN': 
				case 'RU-TAY': 
				case 'RU-UOB': 
				case 'RU-YAN': 
				case 'UA': 
				case 'UA-71': 
				case 'UA-74': 
				case 'UA-77': 
				case 'UA-12': 
				case 'UA-14': 
				case 'UA-26': 
				case 'UA-63': 
				case 'UA-65': 
				case 'UA-68': 
				case 'UA-35': 
				case 'UA-32': 
				case 'UA-09': 
				case 'UA-46': 
				case 'UA-48': 
				case 'UA-51': 
				case 'UA-53': 
				case 'UA-56': 
				case 'UA-59': 
				case 'UA-61': 
				case 'UA-05': 
				case 'UA-07': 
				case 'UA-21': 
				case 'UA-23': 
				case 'UA-18': 
				case 'UA-43': 
				case 'UA-30': 
				case 'UA-40': 
				case 'FR': 
				case 'FR-A': 
				case 'FR-67': 
				case 'FR-68': 
				case 'FR-B': 
				case 'FR-79': 
				case 'FR-24': 
				case 'FR-33': 
				case 'FR-40': 
				case 'FR-47': 
				case 'FR-64': 
				case 'FR-C': 
				case 'FR-03': 
				case 'FR-15': 
				case 'FR-43': 
				case 'FR-63': 
				case 'FR-P': 
				case 'FR-14': 
				case 'FR-50': 
				case 'FR-61': 
				case 'FR-D': 
				case 'FR-21': 
				case 'FR-58': 
				case 'FR-71': 
				case 'FR-89': 
				case 'FR-E': 
				case 'FR-22': 
				case 'FR-29': 
				case 'FR-35': 
				case 'FR-56': 
				case 'FR-F': 
				case 'FR-18': 
				case 'FR-28': 
				case 'FR-36': 
				case 'FR-37': 
				case 'FR-41': 
				case 'FR-45': 
				case 'FR-G': 
				case 'FR-08': 
				case 'FR-10': 
				case 'FR-52': 
				case 'FR-51': 
				case 'FR-H': 
				case 'FR-2A': 
				case 'FR-2B': 
				case 'FR-I': 
				case 'FR-25': 
				case 'FR-70': 
				case 'FR-39': 
				case 'FR-90': 
				case 'FR-Q': 
				case 'FR-27': 
				case 'FR-76': 
				case 'FR-J': 
				case 'FR-91': 
				case 'FR-92': 
				case 'FR-75': 
				case 'FR-77': 
				case 'FR-93': 
				case 'FR-94': 
				case 'FR-95': 
				case 'FR-78': 
				case 'FR-K': 
				case 'FR-11': 
				case 'FR-30': 
				case 'FR-34': 
				case 'FR-48': 
				case 'FR-66': 
				case 'FR-L': 
				case 'FR-19': 
				case 'FR-23': 
				case 'FR-87': 
				case 'FR-M': 
				case 'FR-54': 
				case 'FR-55': 
				case 'FR-57': 
				case 'FR-88': 
				case 'FR-N': 
				case 'FR-09': 
				case 'FR-12': 
				case 'FR-32': 
				case 'FR-31': 
				case 'FR-65': 
				case 'FR-46': 
				case 'FR-81': 
				case 'FR-82': 
				case 'FR-O': 
				case 'FR-59': 
				case 'FR-62': 
				case 'FR-R': 
				case 'FR-44': 
				case 'FR-49': 
				case 'FR-53': 
				case 'FR-72': 
				case 'FR-85': 
				case 'FR-S': 
				case 'FR-02': 
				case 'FR-60': 
				case 'FR-80': 
				case 'FR-T': 
				case 'FR-16': 
				case 'FR-17': 
				case 'FR-86': 
				case 'FR-U': 
				case 'FR-04': 
				case 'FR-06': 
				case 'FR-13': 
				case 'FR-05': 
				case 'FR-83': 
				case 'FR-84': 
				case 'FR-V': 
				case 'FR-01': 
				case 'FR-07': 
				case 'FR-26': 
				case 'FR-74': 
				case 'FR-38': 
				case 'FR-42': 
				case 'FR-69': 
				case 'FR-73': 
				case 'FR-GP': 
				case 'FR-GF': 
				case 'FR-MQ': 
				case 'FR-RE': 
				case 'FR-YT': 
				case 'FR-PM': 
				case 'FR-NC': 
				case 'FR-PF': 
				case 'FR-TF': 
				case 'FR-WF': 
				case 'ES': 
				case 'ES-AN': 
				case 'ES-AL': 
				case 'ES-CA': 
				case 'ES-CO': 
				case 'ES-GR': 
				case 'ES-H': 
				case 'ES-J': 
				case 'ES-MA': 
				case 'ES-SE': 
				case 'ES-AR': 
				case 'ES-HU': 
				case 'ES-TE': 
				case 'ES-Z': 
				case 'ES-O': 
				case 'ES-CN': 
				case 'ES-GC': 
				case 'ES-TF': 
				case 'ES-S': 
				case 'ES-CM': 
				case 'ES-AB': 
				case 'ES-CR': 
				case 'ES-CU': 
				case 'ES-GU': 
				case 'ES-TO': 
				case 'ES-CL': 
				case 'ES-AV': 
				case 'ES-BU': 
				case 'ES-LE': 
				case 'ES-P': 
				case 'ES-SA': 
				case 'ES-SG': 
				case 'ES-SO': 
				case 'ES-VA': 
				case 'ES-ZA': 
				case 'ES-CT': 
				case 'ES-B': 
				case 'ES-GE': 
				case 'ES-L': 
				case 'ES-T': 
				case 'ES-EX': 
				case 'ES-BA': 
				case 'ES-CC': 
				case 'ES-GA': 
				case 'ES-C': 
				case 'ES-LU': 
				case 'ES-OR': 
				case 'ES-PO': 
				case 'ES-PM': 
				case 'ES-LO': 
				case 'ES-M': 
				case 'ES-MU': 
				case 'ES-NA': 
				case 'ES-PV': 
				case 'ES-VI': 
				case 'ES-SS': 
				case 'ES-BI': 
				case 'ES-VC': 
				case 'ES-A': 
				case 'ES-CS': 
				case 'ES-V': 
				case 'SE': 
				case 'SE-K': 
				case 'SE-W': 
				case 'SE-I': 
				case 'SE-X': 
				case 'SE-N': 
				case 'SE-Z': 
				case 'SE-F': 
				case 'SE-H': 
				case 'SE-G': 
				case 'SE-BD': 
				case 'SE-M': 
				case 'SE-AB': 
				case 'SE-D': 
				case 'SE-C': 
				case 'SE-S': 
				case 'SE-AC': 
				case 'SE-Y': 
				case 'SE-U': 
				case 'SE-O': 
				case 'SE-T': 
				case 'SE-E': 
				case 'NO': 
				case 'NO-02': 
				case 'NO-09': 
				case 'NO-06': 
				case 'NO-20': 
				case 'NO-04': 
				case 'NO-12': 
				case 'NO-15': 
				case 'NO-18': 
				case 'NO-17': 
				case 'NO-05': 
				case 'NO-03': 
				case 'NO-11': 
				case 'NO-14': 
				case 'NO-16': 
				case 'NO-08': 
				case 'NO-19': 
				case 'NO-10': 
				case 'NO-07': 
				case 'NO-01': 
				case 'NO-22': 
				case 'NO-21': 
				case 'DE': 
				case 'DE-BW': 
				case 'DE-BY': 
				case 'DE-BE': 
				case 'DE-BB': 
				case 'DE-HB': 
				case 'DE-HH': 
				case 'DE-HE': 
				case 'DE-MV': 
				case 'DE-NI': 
				case 'DE-NW': 
				case 'DE-RP': 
				case 'DE-SL': 
				case 'DE-SN': 
				case 'DE-ST': 
				case 'DE-SH': 
				case 'DE-TH': 
				case 'FI': 
				case 'FI-AL': 
				case 'FI-ES': 
				case 'FI-IS': 
				case 'FI-LL': 
				case 'FI-LS': 
				case 'FI-OL': 
				case 'PL': 
				case 'PL-BP': 
				case 'PL-BK': 
				case 'PL-BB': 
				case 'PL-BY': 
				case 'PL-CH': 
				case 'PL-CI': 
				case 'PL-CZ': 
				case 'PL-EL': 
				case 'PL-GD': 
				case 'PL-GO': 
				case 'PL-JG': 
				case 'PL-KL': 
				case 'PL-KA': 
				case 'PL-KI': 
				case 'PL-KN': 
				case 'PL-KO': 
				case 'PL-KR': 
				case 'PL-KS': 
				case 'PL-LG': 
				case 'PL-LE': 
				case 'PL-LU': 
				case 'PL-LO': 
				case 'PL-LD': 
				case 'PL-NS': 
				case 'PL-OL': 
				case 'PL-OP': 
				case 'PL-OS': 
				case 'PL-PI': 
				case 'PL-PT': 
				case 'PL-PL': 
				case 'PL-PO': 
				case 'PL-PR': 
				case 'PL-RA': 
				case 'PL-RZ': 
				case 'PL-SE': 
				case 'PL-SI': 
				case 'PL-SK': 
				case 'PL-SL': 
				case 'PL-SU': 
				case 'PL-SZ': 
				case 'PL-TG': 
				case 'PL-TA': 
				case 'PL-TO': 
				case 'PL-WB': 
				case 'PL-WA': 
				case 'PL-WL': 
				case 'PL-WR': 
				case 'PL-ZA': 
				case 'PL-ZG': 
				case 'IT': 
				case 'IT-65': 
				case 'IT-CH': 
				case 'IT-AQ': 
				case 'IT-PE': 
				case 'IT-TE': 
				case 'IT-77': 
				case 'IT-MT': 
				case 'IT-PZ': 
				case 'IT-78': 
				case 'IT-CZ': 
				case 'IT-CS': 
				case 'IT-KR': 
				case 'IT-RC': 
				case 'IT-W': 
				case 'IT-72': 
				case 'IT-AV': 
				case 'IT-BN': 
				case 'IT-CE': 
				case 'IT-NA': 
				case 'IT-SA': 
				case 'IT-45': 
				case 'IT-BO': 
				case 'IT-FE': 
				case 'IT-FO': 
				case 'IT-MO': 
				case 'IT-PR': 
				case 'IT-PC': 
				case 'IT-RA': 
				case 'IT-RE': 
				case 'IT-RN': 
				case 'IT-36': 
				case 'IT-GO': 
				case 'IT-PN': 
				case 'IT-TS': 
				case 'IT-UD': 
				case 'IT-62': 
				case 'IT-FR': 
				case 'IT-LT': 
				case 'IT-RI': 
				case 'IT-RM': 
				case 'IT-VT': 
				case 'IT-42': 
				case 'IT-GE': 
				case 'IT-IM': 
				case 'IT-SP': 
				case 'IT-SV': 
				case 'IT-25': 
				case 'IT-BG': 
				case 'IT-BS': 
				case 'IT-CO': 
				case 'IT-CR': 
				case 'IT-LC': 
				case 'IT-LO': 
				case 'IT-MN': 
				case 'IT-MI': 
				case 'IT-PV': 
				case 'IT-SO': 
				case 'IT-VA': 
				case 'IT-57': 
				case 'IT-AN': 
				case 'IT-AP': 
				case 'IT-MC': 
				case 'IT-PS': 
				case 'IT-67': 
				case 'IT-CB': 
				case 'IT-IS': 
				case 'IT-21': 
				case 'IT-AL': 
				case 'IT-AT': 
				case 'IT-BI': 
				case 'IT-CN': 
				case 'IT-NO': 
				case 'IT-TO': 
				case 'IT-VB': 
				case 'IT-VC': 
				case 'IT-75': 
				case 'IT-BA': 
				case 'IT-BR': 
				case 'IT-FG': 
				case 'IT-LE': 
				case 'IT-TA': 
				case 'IT-88': 
				case 'IT-CA': 
				case 'IT-NU': 
				case 'IT-OR': 
				case 'IT-SS': 
				case 'IT-82': 
				case 'IT-AG': 
				case 'IT-CL': 
				case 'IT-CT': 
				case 'IT-EN': 
				case 'IT-ME': 
				case 'IT-PA': 
				case 'IT-RG': 
				case 'IT-SR': 
				case 'IT-TP': 
				case 'IT-52': 
				case 'IT-AR': 
				case 'IT-FI': 
				case 'IT-GR': 
				case 'IT-LI': 
				case 'IT-LU': 
				case 'IT-MS': 
				case 'IT-PI': 
				case 'IT-PT': 
				case 'IT-PO': 
				case 'IT-SI': 
				case 'IT-32': 
				case 'IT-BZ': 
				case 'IT-TN': 
				case 'IT-55': 
				case 'IT-PG': 
				case 'IT-TR': 
				case 'IT-23': 
				case 'IT-AO': 
				case 'IT-34': 
				case 'IT-BL': 
				case 'IT-PD': 
				case 'IT-RO': 
				case 'IT-TV': 
				case 'IT-VE': 
				case 'IT-VR': 
				case 'IT-VI': 
				case 'GB': 
				case 'GB-CHA': 
				case 'GB-GSY': 
				case 'GB-JSY': 
				case 'GB-ENG': 
				case 'GB-BDG': 
				case 'GB-BNE': 
				case 'GB-BNS': 
				case 'GB-BAS': 
				case 'GB-BDF': 
				case 'GB-BEX': 
				case 'GB-BIR': 
				case 'GB-BBD': 
				case 'GB-BPL': 
				case 'GB-BOL': 
				case 'GB-BMH': 
				case 'GB-BRC': 
				case 'GB-BRD': 
				case 'GB-BEN': 
				case 'GB-BNH': 
				case 'GB-BST': 
				case 'GB-BRY': 
				case 'GB-BKM': 
				case 'GB-BUR': 
				case 'GB-CLD': 
				case 'GB-CAM': 
				case 'GB-CMD': 
				case 'GB-CHS': 
				case 'GB-CON': 
				case 'GB-COV': 
				case 'GB-CRY': 
				case 'GB-CMA': 
				case 'GB-DAL': 
				case 'GB-DER': 
				case 'GB-DBY': 
				case 'GB-DEV': 
				case 'GB-DNC': 
				case 'GB-DOR': 
				case 'GB-DUD': 
				case 'GB-DUR': 
				case 'GB-EAL': 
				case 'GB-ERY': 
				case 'GB-ESX': 
				case 'GB-ENF': 
				case 'GB-ESS': 
				case 'GB-GAT': 
				case 'GB-GLS': 
				case 'GB-GRE': 
				case 'GB-HCK': 
				case 'GB-HAL': 
				case 'GB-HMF': 
				case 'GB-HAM': 
				case 'GB-HRY': 
				case 'GB-HRW': 
				case 'GB-HPL': 
				case 'GB-HAV': 
				case 'GB-HEF': 
				case 'GB-HRT	': 
				case 'GB-HIL': 
				case 'GB-HNS': 
				case 'GB-IOW': 
				case 'GB-IOS': 
				case 'GB-ISL': 
				case 'GB-KEC': 
				case 'GB-KEN': 
				case 'GB-KHL': 
				case 'GB-KTT': 
				case 'GB-KIR': 
				case 'GB-KWL': 
				case 'GB-LBH': 
				case 'GB-LAN': 
				case 'GB-LDS': 
				case 'GB-LCE': 
				case 'GB-LEC': 
				case 'GB-LEW': 
				case 'GB-LIN': 
				case 'GB-LIV': 
				case 'GB-LND': 
				case 'GB-LUT': 
				case 'GB-MAN': 
				case 'GB-MDW': 
				case 'GB-MRT': 
				case 'GB-MDB': 
				case 'GB-MIK': 
				case 'GB-NET': 
				case 'GB-NWM': 
				case 'GB-NFK': 
				case 'GB-NEL': 
				case 'GB-NLN': 
				case 'GB-NSM': 
				case 'GB-NTY': 
				case 'GB-NYK': 
				case 'GB-NTH': 
				case 'GB-NBL': 
				case 'GB-NGM': 
				case 'GB-NTT': 
				case 'GB-OLD': 
				case 'GB-OXF': 
				case 'GB-PTE': 
				case 'GB-PLY': 
				case 'GB-POL': 
				case 'GB-POR': 
				case 'GB-RDG': 
				case 'GB-RDB': 
				case 'GB-RCC': 
				case 'GB-RIC': 
				case 'GB-RCH': 
				case 'GB-ROT': 
				case 'GB-RUT': 
				case 'GB-SHN': 
				case 'GB-SLF': 
				case 'GB-SAW': 
				case 'GB-SFT': 
				case 'GB-SHF': 
				case 'GB-SHR': 
				case 'GB-SLG': 
				case 'GB-SOL': 
				case 'GB-SOM': 
				case 'GB-SGC': 
				case 'GB-STY': 
				case 'GB-STH': 
				case 'GB-SOS': 
				case 'GB-SWK': 
				case 'GB-STS': 
				case 'GB-SKP': 
				case 'GB-STT': 
				case 'GB-STE': 
				case 'GB-SFK': 
				case 'GB-SND': 
				case 'GB-SRY': 
				case 'GB-STN': 
				case 'GB-SWD': 
				case 'GB-TAM': 
				case 'GB-TFW': 
				case 'GB-THR': 
				case 'GB-TOB': 
				case 'GB-TWH': 
				case 'GB-TRF': 
				case 'GB-WKF': 
				case 'GB-WLL': 
				case 'GB-WFT': 
				case 'GB-WND': 
				case 'GB-WRT': 
				case 'GB-WAR': 
				case 'GB-WBK': 
				case 'GB-WSX': 
				case 'GB-WSM': 
				case 'GB-WGN': 
				case 'GB-WIL': 
				case 'GB-WNM': 
				case 'GB-WRL': 
				case 'GB-WOK': 
				case 'GB-WLV': 
				case 'GB-WOR': 
				case 'GB-YOR': 
				case 'GB-IOM': 
				case 'GB-NIR': 
				case 'GB-ANT': 
				case 'GB-ARD': 
				case 'GB-ARM': 
				case 'GB-BLA': 
				case 'GB-BLY': 
				case 'GB-BNB': 
				case 'GB-BFS': 
				case 'GB-CKF': 
				case 'GB-CSR': 
				case 'GB-CLR': 
				case 'GB-CKT': 
				case 'GB-CGV': 
				case 'GB-DRY': 
				case 'GB-DOW': 
				case 'GB-DGN': 
				case 'GB-FER': 
				case 'GB-LRN': 
				case 'GB-LMV': 
				case 'GB-LSB': 
				case 'GB-MFT': 
				case 'GB-MYL': 
				case 'GB-NYM': 
				case 'GB-NTA': 
				case 'GB-NDN': 
				case 'GB-OMH': 
				case 'GB-STB': 
				case 'GB-SCT': 
				case 'GB-ABE': 
				case 'GB-ABD': 
				case 'GB-ANS': 
				case 'GB-AGB': 
				case 'GB-CLK': 
				case 'GB-DGY': 
				case 'GB-DND': 
				case 'GB-EAY': 
				case 'GB-EDU': 
				case 'GB-ELN': 
				case 'GB-ERW': 
				case 'GB-EDH': 
				case 'GB-ELS': 
				case 'GB-FAL': 
				case 'GB-FIF': 
				case 'GB-GLG': 
				case 'GB-HLD': 
				case 'GB-IVC': 
				case 'GB-MLN': 
				case 'GB-MRY': 
				case 'GB-NAY': 
				case 'GB-NLK': 
				case 'GB-ORK': 
				case 'GB-PKN': 
				case 'GB-RFW': 
				case 'GB-SCB': 
				case 'GB-ZET': 
				case 'GB-SAY': 
				case 'GB-SLK': 
				case 'GB-STG': 
				case 'GB-WDU': 
				case 'GB-WLN': 
				case 'GB-WLS': 
				case 'GB-BGW': 
				case 'GB-BGE': 
				case 'GB-CAY': 
				case 'GB-CRF': 
				case 'GB-CMN': 
				case 'GB-CGN': 
				case 'GB-CWY': 
				case 'GB-DEN': 
				case 'GB-FLN': 
				case 'GB-GWN': 
				case 'GB-AGY': 
				case 'GB-MTY': 
				case 'GB-MON': 
				case 'GB-NTL': 
				case 'GB-NWP': 
				case 'GB-PEM': 
				case 'GB-POW': 
				case 'GB-RCT': 
				case 'GB-SWA': 
				case 'GB-TOF': 
				case 'GB-VGL': 
				case 'GB-WRX': 
				case 'RO': 
				case 'RO-B': 
				case 'RO-AB': 
				case 'RO-AR': 
				case 'RO-AG': 
				case 'RO-BC': 
				case 'RO-BH': 
				case 'RO-BN': 
				case 'RO-BT': 
				case 'RO-BV': 
				case 'RO-BR': 
				case 'RO-BZ': 
				case 'RO-CS': 
				case 'RO-CL': 
				case 'RO-CJ': 
				case 'RO-CT': 
				case 'RO-CV': 
				case 'RO-DB': 
				case 'RO-DJ': 
				case 'RO-GL': 
				case 'RO-GR': 
				case 'RO-GJ': 
				case 'RO-HR': 
				case 'RO-HD': 
				case 'RO-IL': 
				case 'RO-IS': 
				case 'RO-MM': 
				case 'RO-MH': 
				case 'RO-MS': 
				case 'RO-NT': 
				case 'RO-OT': 
				case 'RO-PH': 
				case 'RO-SM': 
				case 'RO-SJ': 
				case 'RO-SB': 
				case 'RO-SV': 
				case 'RO-TR': 
				case 'RO-TM': 
				case 'RO-TL': 
				case 'RO-VS': 
				case 'RO-VL': 
				case 'RO-VN': 
				case 'BY': 
				case 'BY-BR': 
				case 'BY-HO': 
				case 'BY-HR': 
				case 'BY-MA': 
				case 'BY-MI': 
				case 'BY-VI': 
				case 'GR': 
				case 'GR-I': 
				case 'GR-52': 
				case 'GR-71': 
				case 'GR-55': 
				case 'GR-73': 
				case 'GR-72': 
				case 'GR-IX': 
				case 'GR-A1': 
				case 'GR-VII': 
				case 'GR-13': 
				case 'GR-01': 
				case 'GR-14': 
				case 'GR-III': 
				case 'GR-63': 
				case 'GR-51': 
				case 'GR-56': 
				case 'GR-58': 
				case 'GR-VI': 
				case 'GR-23': 
				case 'GR-22': 
				case 'GR-24': 
				case 'GR-21': 
				case 'GR-IV': 
				case 'GR-31': 
				case 'GR-33': 
				case 'GR-34': 
				case 'GR-32': 
				case 'GR-II': 
				case 'GR-64': 
				case 'GR-53': 
				case 'GR-57': 
				case 'GR-59': 
				case 'GR-61': 
				case 'GR-62': 
				case 'GR-54': 
				case 'GR-XIII': 
				case 'GR-94': 
				case 'GR-91': 
				case 'GR-92': 
				case 'GR-93': 
				case 'GR-XII': 
				case 'GR-81': 
				case 'GR-82': 
				case 'GR-X': 
				case 'GR-11': 
				case 'GR-12': 
				case 'GR-15': 
				case 'GR-16': 
				case 'GR-17': 
				case 'GR-VIII	': 
				case 'GR-05': 
				case 'GR-04': 
				case 'GR-07': 
				case 'GR-06': 
				case 'GR-03': 
				case 'GR-V': 
				case 'GR-41': 
				case 'GR-42': 
				case 'GR-43': 
				case 'GR-44': 
				case 'GR-XI': 
				case 'GR-85': 
				case 'GR-83': 
				case 'GR-84': 
				case 'BG': 
				case 'BG-02': 
				case 'BG-09': 
				case 'BG-04': 
				case 'BG-05': 
				case 'BG-06': 
				case 'BG-07': 
				case 'BG-08': 
				case 'BG-01': 
				case 'BG-03': 
				case 'IS': 
				case 'IS-7': 
				case 'IS-1': 
				case 'IS-6': 
				case 'IS-5': 
				case 'IS-0': 
				case 'IS-8': 
				case 'IS-2': 
				case 'IS-4': 
				case 'IS-3': 
				case 'HU': 
				case 'HU-BU': 
				case 'HU-BK': 
				case 'HU-BA': 
				case 'HU-BE': 
				case 'HU-BZ': 
				case 'HU-CS': 
				case 'HU-FE': 
				case 'HU-GS': 
				case 'HU-HB': 
				case 'HU-HE': 
				case 'HU-JN': 
				case 'HU-KE': 
				case 'HU-NO': 
				case 'HU-PE': 
				case 'HU-SO': 
				case 'HU-SZ': 
				case 'HU-TO': 
				case 'HU-VA': 
				case 'HU-VE': 
				case 'HU-ZA': 
				case 'HU-BC': 
				case 'HU-DE': 
				case 'HU-DU': 
				case 'HU-EG': 
				case 'HU-GY': 
				case 'HU-HV': 
				case 'HU-KV': 
				case 'HU-KM': 
				case 'HU-MI': 
				case 'HU-NK': 
				case 'HU-NY': 
				case 'HU-PS': 
				case 'HU-ST': 
				case 'HU-SN': 
				case 'HU-SD': 
				case 'HU-SF': 
				case 'HU-SS': 
				case 'HU-SK': 
				case 'HU-SH': 
				case 'HU-TB': 
				case 'HU-VM': 
				case 'HU-ZE': 
				case 'PT': 
				case 'PT-01': 
				case 'PT-02': 
				case 'PT-03': 
				case 'PT-04': 
				case 'PT-05': 
				case 'PT-06': 
				case 'PT-07': 
				case 'PT-08': 
				case 'PT-09': 
				case 'PT-10': 
				case 'PT-11': 
				case 'PT-12': 
				case 'PT-13': 
				case 'PT-14': 
				case 'PT-15': 
				case 'PT-16': 
				case 'PT-17': 
				case 'PT-18': 
				case 'PT-20': 
				case 'PT-30': 
				case 'RS': 
				case 'AT': 
				case 'AT-1': 
				case 'AT-2': 
				case 'AT-3': 
				case 'AT-4': 
				case 'AT-5': 
				case 'AT-6': 
				case 'AT-7': 
				case 'AT-8': 
				case 'AT-9': 
				case 'CZ': 
				case 'CZ-PRG': 
				case 'CZ-CJC': 
				case 'CZ-CJM': 
				case 'CZ-CSC': 
				case 'CZ-CSM': 
				case 'CZ-CST': 
				case 'CZ-CVC': 
				case 'CZ-CZC': 
				case 'IE': 
				case 'IE-CP': 
				case 'IE-G': 
				case 'IE-LM': 
				case 'IE-MO': 
				case 'IE-RN': 
				case 'IE-SO': 
				case 'IE-LP': 
				case 'IE-CW': 
				case 'IE-D': 
				case 'IE-KE': 
				case 'IE-KK': 
				case 'IE-LS': 
				case 'IE-LD': 
				case 'IE-LH': 
				case 'IE-MH': 
				case 'IE-OY': 
				case 'IE-WH': 
				case 'IE-WX': 
				case 'IE-WW': 
				case 'IE-M': 
				case 'IE-UP': 
				case 'IE-CN': 
				case 'IE-DL': 
				case 'IE-MN': 
				case 'GE': 
				case 'GE-AB': 
				case 'GE-AJ': 
				case 'GE-BUS': 
				case 'GE-CHI': 
				case 'GE-GAG': 
				case 'GE-GOR': 
				case 'GE-KUT': 
				case 'GE-PTI': 
				case 'GE-RUS': 
				case 'GE-SUI': 
				case 'GE-TBS': 
				case 'GE-TQI': 
				case 'GE-TQV': 
				case 'GE-TSQ': 
				case 'GE-ZUG': 
				case 'GE-01': 
				case 'GE-02': 
				case 'GE-03': 
				case 'GE-04': 
				case 'GE-05': 
				case 'GE-06': 
				case 'GE-07': 
				case 'GE-08': 
				case 'GE-09': 
				case 'GE-10': 
				case 'GE-11': 
				case 'GE-12': 
				case 'GE-13': 
				case 'GE-14': 
				case 'GE-15': 
				case 'GE-16': 
				case 'GE-17': 
				case 'GE-18': 
				case 'GE-19': 
				case 'GE-20': 
				case 'GE-21': 
				case 'GE-22': 
				case 'GE-23': 
				case 'GE-24': 
				case 'GE-25': 
				case 'GE-26': 
				case 'GE-27': 
				case 'GE-28': 
				case 'GE-29': 
				case 'GE-30': 
				case 'GE-31': 
				case 'GE-32': 
				case 'GE-33': 
				case 'GE-34': 
				case 'GE-35': 
				case 'GE-36': 
				case 'GE-37': 
				case 'GE-38': 
				case 'GE-39': 
				case 'GE-40': 
				case 'GE-41': 
				case 'GE-42': 
				case 'GE-43': 
				case 'GE-44': 
				case 'GE-45': 
				case 'GE-46': 
				case 'GE-47': 
				case 'GE-48': 
				case 'GE-49': 
				case 'GE-50': 
				case 'GE-51': 
				case 'GE-52': 
				case 'GE-53': 
				case 'GE-54': 
				case 'GE-55': 
				case 'GE-56': 
				case 'GE-57': 
				case 'GE-58': 
				case 'GE-59': 
				case 'GE-60': 
				case 'GE-61': 
				case 'GE-62': 
				case 'GE-63': 
				case 'LT': 
				case 'LT-AL': 
				case 'LT-KU': 
				case 'LT-KL': 
				case 'LT-MR': 
				case 'LT-PN': 
				case 'LT-SA': 
				case 'LT-TA': 
				case 'LT-TE': 
				case 'LT-UT': 
				case 'LT-VL': 
				case 'LV': 
				case 'LV-AI': 
				case 'LV-AL': 
				case 'LV-BL': 
				case 'LV-BU': 
				case 'LV-CE': 
				case 'LV-DA': 
				case 'LV-DO': 
				case 'LV-GU': 
				case 'LV-JL': 
				case 'LV-JK': 
				case 'LV-KR': 
				case 'LV-KU': 
				case 'LV-LM': 
				case 'LV-LE': 
				case 'LV-LU': 
				case 'LV-MA': 
				case 'LV-OG': 
				case 'LV-PR': 
				case 'LV-RE': 
				case 'LV-RI': 
				case 'LV-SA': 
				case 'LV-TA': 
				case 'LV-TU': 
				case 'LV-VK': 
				case 'LV-VM': 
				case 'LV-VE': 
				case 'LV-DGV': 
				case 'LV-JEL': 
				case 'LV-JUR': 
				case 'LV-LPX': 
				case 'LV-REZ': 
				case 'LV-RIX': 
				case 'LV-VEN': 
				case 'HR': 
				case 'HR-07': 
				case 'HR-12': 
				case 'HR-19': 
				case 'HR-18': 
				case 'HR-04': 
				case 'HR-06': 
				case 'HR-02': 
				case 'HR-09': 
				case 'HR-20': 
				case 'HR-14': 
				case 'HR-11': 
				case 'HR-08': 
				case 'HR-03': 
				case 'HR-17': 
				case 'HR-15': 
				case 'HR-05': 
				case 'HR-10': 
				case 'HR-16': 
				case 'HR-13': 
				case 'HR-01': 
				case 'BA': 
				case 'BA-BIH': 
				case 'BA-SRP': 
				case 'SK': 
				case 'SK-BC': 
				case 'SK-BL': 
				case 'SK-KI': 
				case 'SK-NI': 
				case 'SK-PV': 
				case 'SK-TC': 
				case 'SK-TA': 
				case 'SK-ZI': 
				case 'EE': 
				case 'EE-37': 
				case 'EE-39': 
				case 'EE-44': 
				case 'EE-49': 
				case 'EE-51': 
				case 'EE-57': 
				case 'EE-59': 
				case 'EE-65': 
				case 'EE-67': 
				case 'EE-70': 
				case 'EE-74': 
				case 'EE-78': 
				case 'EE-82': 
				case 'EE-84': 
				case 'EE-86': 
				case 'DK': 
				case 'DK-147': 
				case 'DK-101': 
				case 'DK-040': 
				case 'DK-020': 
				case 'DK-042': 
				case 'DK-015': 
				case 'DK-080': 
				case 'DK-055': 
				case 'DK-065': 
				case 'DK-025': 
				case 'DK-035': 
				case 'DK-050': 
				case 'DK-060': 
				case 'DK-030': 
				case 'DK-076': 
				case 'DK-070': 
				case 'NL': 
				case 'NL-DR': 
				case 'NL-FL': 
				case 'NL-FR': 
				case 'NL-GE': 
				case 'NL-GR': 
				case 'NL-LI': 
				case 'NL-NB': 
				case 'NL-NH': 
				case 'NL-OV': 
				case 'NL-UT': 
				case 'NL-ZE': 
				case 'NL-ZH': 
				case 'CH': 
				case 'CH-AG': 
				case 'CH-AR': 
				case 'CH-AI': 
				case 'CH-BL': 
				case 'CH-BS': 
				case 'CH-BE': 
				case 'CH-FR': 
				case 'CH-GE': 
				case 'CH-GL': 
				case 'CH-GR': 
				case 'CH-JU': 
				case 'CH-LU': 
				case 'CH-NE': 
				case 'CH-NW': 
				case 'CH-OW': 
				case 'CH-SG': 
				case 'CH-SH': 
				case 'CH-SZ': 
				case 'CH-SO': 
				case 'CH-TG': 
				case 'CH-TI': 
				case 'CH-UR': 
				case 'CH-VS': 
				case 'CH-VD': 
				case 'CH-ZG': 
				case 'CH-ZH': 
				case 'MD': 
				case 'MD-BAL': 
				case 'MD-CAH': 
				case 'MD-CHI': 
				case 'MD-DUB': 
				case 'MD-ORH': 
				case 'MD-RIB': 
				case 'MD-SOC': 
				case 'MD-TIG': 
				case 'MD-TIR': 
				case 'MD-UNG': 
				case 'MD-ANE': 
				case 'MD-BAS': 
				case 'MD-BRI': 
				case 'MD-CHL': 
				case 'MD-CAM': 
				case 'MD-CAN': 
				case 'MD-CAI': 
				case 'MD-CAL': 
				case 'MD-CAS': 
				case 'MD-CIA': 
				case 'MD-CIM': 
				case 'MD-COM': 
				case 'MD-CRI': 
				case 'MD-DON': 
				case 'MD-DRO': 
				case 'MD-DBI': 
				case 'MD-EDI': 
				case 'MD-FAL': 
				case 'MD-FLO': 
				case 'MD-GLO': 
				case 'MD-GRI': 
				case 'MD-HIN': 
				case 'MD-IAL': 
				case 'MD-LEO': 
				case 'MD-NIS': 
				case 'MD-OCN': 
				case 'MD-OHI': 
				case 'MD-REZ': 
				case 'MD-RIT': 
				case 'MD-RIS': 
				case 'MD-SIN': 
				case 'MD-SLO': 
				case 'MD-SOA': 
				case 'MD-STR': 
				case 'MD-SOL': 
				case 'MD-STE': 
				case 'MD-TAR': 
				case 'MD-TEL': 
				case 'MD-UGI': 
				case 'MD-VUL': 
				case 'BE': 
				case 'BE-BRU': 
				case 'BE-VLG': 
				case 'BE-VAN': 
				case 'BE-VLI': 
				case 'BE-VOV': 
				case 'BE-VBR': 
				case 'BE-VWV': 
				case 'BE-WAL': 
				case 'BE-WBR': 
				case 'BE-WHT': 
				case 'BE-WLG': 
				case 'BE-WLX': 
				case 'BE-WNA': 
				case 'MK': 
				case 'TR': 
				case 'TR-01': 
				case 'TR-02': 
				case 'TR-03': 
				case 'TR-04': 
				case 'TR-68': 
				case 'TR-05': 
				case 'TR-06': 
				case 'TR-07': 
				case 'TR-75': 
				case 'TR-08': 
				case 'TR-09': 
				case 'TR-10': 
				case 'TR-74': 
				case 'TR-72': 
				case 'TR-69': 
				case 'TR-11': 
				case 'TR-12': 
				case 'TR-13': 
				case 'TR-14': 
				case 'TR-15': 
				case 'TR-16': 
				case 'TR-17': 
				case 'TR-18': 
				case 'TR-19': 
				case 'TR-20': 
				case 'TR-21': 
				case 'TR-22': 
				case 'TR-23': 
				case 'TR-24': 
				case 'TR-25': 
				case 'TR-26': 
				case 'TR-27': 
				case 'TR-28': 
				case 'TR-29': 
				case 'TR-30': 
				case 'TR-31': 
				case 'TR-76': 
				case 'TR-32': 
				case 'TR-33': 
				case 'TR-34': 
				case 'TR-35': 
				case 'TR-46': 
				case 'TR-78': 
				case 'TR-70': 
				case 'TR-36': 
				case 'TR-37': 
				case 'TR-38': 
				case 'TR-71': 
				case 'TR-39': 
				case 'TR-40': 
				case 'TR-79': 
				case 'TR-41': 
				case 'TR-42': 
				case 'TR-43': 
				case 'TR-44': 
				case 'TR-4S': 
				case 'TR-47': 
				case 'TR-48': 
				case 'TR-49': 
				case 'TR-SO': 
				case 'TR-51': 
				case 'TR-52': 
				case 'TR-53': 
				case 'TR-54': 
				case 'TR-SS': 
				case 'TR-56': 
				case 'TR-57': 
				case 'TR-S8': 
				case 'TR-63': 
				case 'TR-73': 
				case 'TR-59': 
				case 'TR-60': 
				case 'TR-61': 
				case 'TR-62': 
				case 'TR-64': 
				case 'TR-65': 
				case 'TR-77': 
				case 'TR-66': 
				case 'TR-67': 
				case 'SI': 
				case 'SI-07': 
				case 'SI-09': 
				case 'SI-11': 
				case 'SI-03': 
				case 'SI-10': 
				case 'SI-12': 
				case 'SI-08': 
				case 'SI-02': 
				case 'SI-01': 
				case 'SI-04': 
				case 'SI-06': 
				case 'SI-05': 
				case 'ME': 
				case 'LU': 
				case 'LU-D': 
				case 'LU-G': 
				case 'LU-L': 
				case 'MT': 
				case 'LI': 
				case 'SM': 
				case 'MC': $EURO += $val;
				break;
				case 'US-CO':
				case 'US-WA':
				case 'US-OR':
				case 'US-ID':
				case 'US-NV':
				case 'US-UT':
				case 'US-AZ':
				case 'US-NM':
				case 'US-WY':
				case 'US-MT': $WEST += $val;
				break;
				case 'US-TX':
				case 'US-AR':
				case 'US-OK':
				case 'US-LA':
				case 'US-TN':
				case 'US-MS':
				case 'US-AL':
				case 'US-GA':
				case 'US-FL':
				case 'US-SC':
				case 'US-NC':
				case 'US-KY':
				case 'US-VA': $SOUTH += $val;
				break;
				case 'US-ND':
				case 'US-SD':
				case 'US-NE':
				case 'US-MN':
				case 'US-IA':
				case 'US-MO':
				case 'US-WI':
				case 'US-IL':
				case 'US-IN':
				case 'US-MI':
				case 'US-OH': $MIDWEST += $val;
				break;
				case 'US-WV':
				case 'US-PA':
				case 'US-MD':
				case 'US-DE':
				case 'US-NJ':
				case 'US-NY': $EAST += $val;
				break;
				case 'US-CT':
				case 'US-MA':
				case 'US-RI':
				case 'US-VT':
				case 'US-NH':
				case 'US-ME': $NEWENGLAND += $val;
				break;
				case '':
				case 'Unknown': $Unknown += $val;
				break;
				case 'US': $USOther += $val;
				break;
				case 'Known unknown': $knownUnknown += $val;
				break;
				default: $other += $val;
			}
		}
		
		$chrroot = $CALIFORNIA.":".$WEST.":".$SOUTH.":".$MIDWEST.":".$EAST.":".$NEWENGLAND.":".$MEX.":".$CAN.":".$EURO.":".$USOther.":".$Unknown.":".$other.":";
		//unset($chrroot);
		return $chrroot;
	}
	
	public function addGenerationFlag(&$analysisFileOutput,$gen)
	{
		//Do Nothing
	}
}
?>